spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_user_db?createDatabaseIfNotExist=true
    username: root
    password: Mysql@1234

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
